/**
 * Every literal string shown by a component lives here, so that nothing is
 * scattered across the codebase. There is no i18n system yet (the PRD only
 * requires the README in three languages); this is the containment measure
 * until that decision is made. Swapping this module for a real i18n layer
 * later should not require touching any component.
 */
export const strings = {
  date: {
    week: (weekNumber: number) => `Week ${weekNumber}`,
  },
  weather: {
    stale: 'Outdated',
    unavailable: 'Weather unavailable',
    label: (locationLabel: string, temperature: number, conditionLabel: string) =>
      `${Math.round(temperature)} degrees, ${conditionLabel}, ${locationLabel}`,
  },
  greeting: {
    morning: 'Good morning, {name}',
    afternoon: 'Good afternoon, {name}',
    evening: 'Good evening, {name}',
    night: 'Good night, {name}',
  },
  serviceWorker: {
    updateAvailable: 'A new version is available — reload to update.',
    reload: 'Reload',
    dismiss: 'Dismiss',
  },
  settings: {
    persistFailed:
      "Your changes couldn't be saved — storage is full. Export your configuration to avoid losing changes.",
    persistFailedBannerCta: 'Open Settings → Data',
    title: 'Settings',
    openSettingsShortcut: 'Open settings',
    nav: {
      appearance: 'Appearance',
      search: 'Search',
      tabsAndLinks: 'Tabs & links',
      widgets: 'Widgets',
      data: 'Data',
    },
    close: 'Close',
    undo: 'Undo',
    redo: 'Redo',
    comingSoon: 'This section is not implemented yet — it arrives in a later phase.',
    tabsLinks: {
      helpTitle: 'Mnemonic shortcut keys',
      helpIntro:
        "Mark a letter in a link's name with '&' to make it the shortcut key. Skip it and the first free letter in the name is used automatically. Use '&&' for a literal ampersand.",
      helpExamples: [
        { input: 'Reddit', description: 'no & — key assigned automatically' },
        { input: '&Reddit', description: "claims 'r'" },
        { input: 'Git&Hub', description: "shown as GitHub, claims 'h'" },
        { input: 'R&&D', description: 'shown as R&D, no key claimed' },
        { input: 'T&elegram', description: "claims 'e'" },
        { input: '&1abc', description: 'digits are not valid keys, no key claimed' },
        { input: 'Àl&bums', description: "claims 'b'" },
      ],
      tabsHeading: 'Tabs',
      addTab: 'Add tab',
      tabNameLabel: 'Tab name',
      tabIconLabel: 'Icon name',
      customFlavourLabel: 'Custom colour flavour for this tab',
      customFlavourHint:
        'This tab uses its own light/dark flavour pair instead of the global one, and still follows your system\'s light/dark mode.',
      untitledTab: 'Untitled tab',
      deleteTab: (name: string) => `Delete tab "${name}"`,
      noTabs: 'No tabs yet — add one to get started.',
      groupsHeading: 'Groups',
      addGroup: 'Add group',
      groupNameLabel: 'Group name',
      groupIconLabel: 'Icon name',
      untitledGroup: 'Untitled group',
      deleteGroup: (name: string) => `Delete group "${name}"`,
      collapseGroup: (name: string) => `Collapse group "${name}"`,
      expandGroup: (name: string) => `Expand group "${name}"`,
      noGroups: 'No groups yet — add one to organise links.',
      linksHeading: 'Links',
      addLink: 'Add link',
      linkNameLabel: 'Link name',
      linkUrlLabel: 'URL',
      linkIconLabel: 'Icon name',
      linkNewTab: 'Open in a new tab',
      untitledLink: 'Untitled link',
      deleteLink: (name: string) => `Delete link "${name}"`,
      noLinks: 'No links yet — add one below.',
      dragHandle: 'Drag to reorder, or press Alt+Arrow keys',
      delete: 'Delete',
      emptyNameWarning: "This name is empty and won't be saved until you enter one.",
      urlRejected: 'This URL is not allowed. Only http, https and mailto links can be saved.',
      mnemonicConflict: (winnerName: string) =>
        `"${winnerName}" already uses this key — pick a different letter.`,
      unassignedCount: (n: number) =>
        n === 1
          ? '1 link in this tab has no shortcut key.'
          : `${n} links in this tab have no shortcut key.`,
      moved: (name: string, position: number, container?: string) =>
        container
          ? `${name} moved to position ${position} in ${container}`
          : `${name} moved to position ${position}`,
      iconHelpSummary: 'Which icon names can I use?',
      iconHelpIntro: 'Icon names come from the Tabler icon set — browse the full set at',
      iconHelpAvailable:
        'The names below are bundled locally and work offline. Any other valid Tabler name still works, but is fetched on demand from the Iconify API (api.iconify.design) the first time it is shown.',
    },
    widgets: {
      slotLabels: {
        'header-left': 'top-left header',
        'header-center': 'top-center header',
        'header-right': 'top-right header',
        'footer-left': 'bottom-left footer',
        'footer-center': 'bottom-center footer',
        'footer-right': 'bottom-right footer',
      },
      typeLabels: {
        clock: 'Clock',
        date: 'Date',
        weather: 'Weather',
        greeting: 'Greeting',
      },
      moved: (name: string, slotLabel: string, position: number) =>
        `${name} moved to ${slotLabel}, position ${position}`,
      emptySlot: 'No widgets in this position yet.',
      addWidget: 'Add widget',
      addWidgetLabel: (typeLabel: string) => `Add ${typeLabel} widget`,
      enableWidget: (name: string) => `Enable ${name}`,
      dragHandle: 'Drag to reorder, or press Alt+Arrow keys to reorder or move between positions',
      deleteWidget: (name: string) => `Delete ${name} widget`,
      delete: 'Delete',
      labelFieldLabel: 'Label',
      timezoneLabel: 'Timezone',
      timezoneInvalid: (value: string) => `'${value}' is not a valid IANA timezone.`,
      localeLabel: 'Locale',
      localeInvalid: (value: string) => `'${value}' is not a valid locale.`,
      unitsLabel: 'Units',
      unitsMetric: 'Metric',
      unitsImperial: 'Imperial',
      refreshMinutesLabel: 'Refresh interval (minutes)',
      hour12Label: '12-hour clock',
      showSecondsLabel: 'Show seconds',
      dateStyleLabel: 'Style',
      capitaliseLabel: 'Capitalise first letter',
      showWeekNumberLabel: 'Show week number',
      nameFieldLabel: 'Name',
      locationHeading: 'Location',
      citySearchLabel: 'Search for a city',
      citySearchPlaceholder: 'Type at least 3 characters…',
      citySearchSearching: 'Searching…',
      citySearchNoResults: 'No results',
      citySearchError: 'Search failed — try again or enter coordinates manually.',
      citySearchResultsLabel: 'City search results',
      latitudeLabel: 'Latitude (manual)',
      longitudeLabel: 'Longitude (manual)',
    },
    search: {
      heading: 'Search engines',
      addEngine: 'Add engine',
      bangLabel: 'Bang',
      bangHint: "Short code used to pick this engine, e.g. type '!d' in search.",
      nameLabel: 'Name',
      templateLabel: 'URL template',
      templatePlaceholder: 'https://example.com/search?q={query}',
      templateHint: "Use '{query}' where the search text should go.",
      iconLabel: 'Icon name (optional)',
      untitledEngine: 'Untitled engine',
      deleteEngine: (name: string) => `Delete engine "${name}"`,
      delete: 'Delete',
      dragHandle: 'Drag to reorder, or press Alt+Arrow keys',
      noEngines: 'No search engines yet — add one to get started.',
      bangEmptyWarning: "This bang is empty and won't be saved until you enter one.",
      bangDuplicateWarning: (bang: string) =>
        `'${bang}' is already used by another engine — pick a different one.`,
      templateRejected: 'This URL is not allowed. Only http, https and mailto links can be saved.',
      templateMissingPlaceholder: "The URL template must include '{query}' where the search text should go.",
      defaultEngineLabel: 'Default',
      defaultEngineHint: 'Used when no bang is given.',
      cannotDeleteLastEngine: 'At least one search engine is required.',
      detectUrlsLabel: 'Detect direct URLs',
      detectUrlsHint: 'Input that looks like a URL navigates there instead of searching.',
      suggestFromLinksLabel: 'Suggest matching links',
      suggestFromLinksHint: 'Show links from your tabs as suggestions while searching.',
      behaviourHeading: 'Behaviour',
      moved: (name: string, position: number) => `${name} moved to position ${position}`,
    },
    appearance: {
      pageTitleLabel: 'Page title',
      pageTitleHint: 'Shown in the browser tab.',
      flavourHeading: 'Colour flavour',
      flavourIntro:
        'The palette follows your system’s light/dark mode automatically; pick which flavour is used for each.',
      lightFlavourLabel: 'Light mode flavour',
      darkFlavourLabel: 'Dark mode flavour',
      fallbackFlavourLabel: 'Fallback flavour',
      fallbackFlavourHint: 'Used when the browser can’t tell light from dark. Must be a dark flavour.',
      flavourNames: {
        'dsp-dawn': 'Dawn (light)',
        'dsp-dusk': 'Dusk (soft dark)',
        'dsp-night': 'Night (medium dark)',
        'dsp-abyss': 'Abyss (deep dark)',
      },
      kindLabel: 'Backdrop',
      kindNone: 'None',
      kindSolid: 'Solid colour',
      kindImage: 'Image',
      deployedHeading: 'Bundled wallpapers',
      deployedEmpty: 'No bundled wallpapers yet — choose a file instead.',
      deployedListLabel: 'Bundled wallpaper',
      chooseFile: 'Choose local file…',
      chooseFileHint: 'Stored in your browser (IndexedDB), never uploaded anywhere.',
      currentSourceLabel: 'Current wallpaper',
      currentSourceNone: 'None selected',
      clearWallpaper: 'Remove wallpaper',
      wallpaperSizeWarning: (mb: number) =>
        `This image is ${mb.toFixed(1)} MB — large wallpapers can slow down the first paint. It will still be used.`,
      staticFallbackLabel: 'Static fallback image',
      staticFallbackHint:
        'Shown instead of the animated wallpaper when the visitor prefers reduced motion.',
      staticFallbackPathPlaceholder: 'wallpapers/fallback.jpg',
      staticFallbackChooseFile: 'Choose local fallback file…',
      staticFallbackClear: 'Clear fallback',
      staticFallbackMissing:
        'This wallpaper looks animated but has no static fallback set — visitors who prefer reduced motion will still see the animation.',
      fitLabel: 'Fit',
      fitCover: 'Cover',
      fitContain: 'Contain',
      fitTile: 'Tile',
      blurLabel: 'Blur (px)',
      opacityLabel: 'Opacity',
      indexLoadFailed: 'Could not load the bundled wallpaper list.',
      contentWidthLabel: 'Page width',
      contentWidthModeFull: 'Full screen',
      contentWidthModePercent: 'Percentage',
      contentWidthModeFixed: 'Fixed width',
      contentWidthPercentLabel: 'Width (%)',
      contentWidthFixedLabel: 'Width (px)',
    },
    data: {
      exportHeading: 'Export',
      exportButton: 'Export configuration',
      idbWallpaperExportWarning:
        'Your configuration references wallpapers stored only in this browser. They will not be included in the export and will be missing if you import this file into another browser.',
      importHeading: 'Import',
      importButton: 'Choose file to import…',
      importNotJson: 'This file is not valid JSON — choose a different file.',
      importPreviewHeading: 'Import preview',
      importPreviewSummary: (tabs: number, links: number) =>
        `This file contains ${tabs} ${tabs === 1 ? 'tab' : 'tabs'} and ${links} ${links === 1 ? 'link' : 'links'}.`,
      importPreviewErrorsHeading: 'Issues found while reading this file',
      importConfirm: 'Confirm import',
      importCancel: 'Cancel',
      importSuccess: 'Configuration imported.',
      resetHeading: 'Reset',
      resetButton: 'Reset to defaults',
      resetConfirm: (tabs: number, links: number) =>
        `This will remove ${tabs} ${tabs === 1 ? 'tab' : 'tabs'} and ${links} ${links === 1 ? 'link' : 'links'}, restoring the default configuration. A backup of your current configuration is kept.`,
      resetConfirmButton: 'Yes, reset',
      resetCancel: 'Cancel',
    },
  },
  themeEditor: {
    commandLabel: 'Customize theme',
    title: 'Customize theme',
    editingFlavour: (flavour: string) => `Editing colours for the active flavour: ${flavour}`,
    hint:
      'Colour overrides apply on top of whichever flavour is active (light or dark) — they are not saved per-flavour.',
    iconLabel: 'Icon',
    // Human-friendly labels for the raw Catppuccin-style palette token
    // names (see types/palette.ts), named after their default semantic
    // role in flavours.css where one exists. Several tokens (rosewater,
    // flamingo, pink, maroon, peach, teal, sky, sapphire, overlay2,
    // overlay0, mantle) aren't wired to any semantic token by default —
    // they're kept under their original name since inventing a role for
    // them would be misleading.
    tokenNames: {
      rosewater: 'Rosewater',
      flamingo: 'Flamingo',
      pink: 'Pink',
      mauve: 'Mnemonic',
      red: 'Danger',
      maroon: 'Maroon',
      peach: 'Peach',
      yellow: 'Warning',
      green: 'Success',
      teal: 'Teal',
      sky: 'Sky',
      sapphire: 'Sapphire',
      blue: 'Info',
      lavender: 'Accent (muted)',
      text: 'Primary text',
      subtext1: 'Secondary text',
      subtext0: 'Muted text',
      overlay2: 'Overlay 2',
      overlay1: 'Faint text',
      overlay0: 'Overlay 0',
      surface2: 'Hover surface / strong border',
      surface1: 'Overlay surface / subtle border',
      surface0: 'Raised surface',
      base: 'Page background',
      mantle: 'Mantle',
      crust: 'Sunken surface',
    },
    resetToken: 'Reset',
    resetAll: 'Reset all overrides',
    downloadButton: 'Download theme',
    downloadHint: 'Saves a small JSON file with just your colour overrides.',
    importFileLabel: 'Import from file…',
    importPasteHeading: 'Or paste theme JSON',
    importPasteHint:
      'Paste a theme file\'s contents (e.g. copied from another browser\'s saved configuration) here.',
    importPastePlaceholder: '{ "overrides": { "mauve": "#a315c9" } }',
    importApply: 'Apply',
    importCancel: 'Cancel',
    importInvalid: 'This is not valid theme JSON.',
    importPreview: (count: number) => (count === 1 ? '1 colour will be applied.' : `${count} colours will be applied.`),
    importUnknownKeys: (keys: string[]) => `Ignored unknown token(s): ${keys.join(', ')}`,
    importSuccess: 'Theme applied.',
  },
} as const;
